# Generated by Django 5.2.3 on 2025-06-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsapp',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventsapp',
            name='ticket',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventsapp',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventsapp',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventsapp.eventsapp')),
            ],
        ),
    ]
